### ISSUE TITLE
Problem with compiling 

### ISSUE THREAD

**Issue by bananacakestudio** [FabioDominio/kinect2grabber#1]
When I'm trying to build ALL_BUILD I'm getting this errors
![image](https://cloud.githubusercontent.com/assets/15315068/21179773/d4b434f2-c1f5-11e6-8a63-042947d229a4.png)

I need this program to save RGB and Depth image to png for my Engineering Thesis, but I have no idea how to solve it, because I'm a little bit newbie in C++, so any solution to this problem would be appreciated.

**Comment by FabioDominio** [comment]
Hi, according to your image it seems you are trying to compile the project in 32 bits while the kinect library you are linking to is the 64 bits version.

Try to select the x64 version of Visual Studio when you import the CMake project in CMake and rebuild everything.

Also, check in CMake that the Kinect library is correctly found, in case of errors CMake should report it.

In any case, if you just need to grab data from Kinect just download the pre-compiled version in the release section.

Bests.

**Comment by bananacakestudio** [comment]
Hi again! 

First I would like to thank you a lot for helping me out and for this awesome grabber! The problem was that I selected the x86 version of Visual Studio when I imported the CMake project. 

Now I got another problem and I'm counting on you again! 😃 I'm a little bit newbie in C++ as I said before and I want to change the code to save the Depth image to UINT16 (I need to get precise distance in mm in Matlab, with UINT8 I get the distance in cm and it's not that precise), but I don't have any clue how to 😞 I tried commenting this `depthMat.convertTo(depthBuffer, CV_8U, 255.0/ maxDepth);` and changing here `Mat depthMat(DEPTH_HEIGHT, DEPTH_WIDTH, CV_16U);
Mat depthBuffer(DEPTH_HEIGHT, DEPTH_WIDTH, CV_8U);` to CV_16U, but then I get gray screen where the depth image is. I will be very thankful if you could help me somehow to get this UINT16 on the depth image. 

Cheers!

**Comment by FabioDominio** [comment]
Hi, I guess you are confusing "depth image" with "depth map". In my code by "depth map" I mean the matrix whose entries are the measured depths in mm of the framed scene, and by "depth image" the grayscale representation of the depth map in order to be displayed as a grayscale image, as both openCV and most softwares as well can only display 8-bit grayscale images.

Since you actually need to process the acquired depth maps in Matlab, you just have to store the depth maps (already in mm) as simple text file and import them in matlab with "importdata" or a similar command.

Have fun!
